defmodule Mix.Tasks.Assets.Vendor do
  @moduledoc "Downloads vendored JS files (heroicons) for the asset pipeline."
  @shortdoc "Downloads vendored JS dependencies"

  use Mix.Task

  @vendor_dir "assets/vendor"
  @files []

  @impl true
  def run(_args) do
    File.mkdir_p!(@vendor_dir)
    Enum.each(@files, &download_vendor_file/1)
    ensure_heroicons_plugin()
  end

  defp download_vendor_file({filename, url}) do
    dest = Path.join(@vendor_dir, filename)

    if File.exists?(dest) do
      Mix.shell().info("#{filename} already exists, skipping")
    else
      Mix.shell().info("Downloading #{filename}...")

      case System.cmd("curl", ["-sL", "-o", dest, url]) do
        {_, 0} -> Mix.shell().info("  -> #{dest}")
        {err, _} -> Mix.raise("Failed to download #{filename}: #{err}")
      end
    end
  end

  defp ensure_heroicons_plugin do
    heroicons = Path.join(@vendor_dir, "heroicons.js")

    unless File.exists?(heroicons) do
      Mix.shell().info("Generating heroicons.js Tailwind plugin...")
      File.write!(heroicons, heroicons_plugin())
      Mix.shell().info("  -> #{heroicons}")
    end
  end

  defp heroicons_plugin do
    """
    // Heroicons Tailwind v4 plugin
    // Generated by mix assets.vendor -- reads SVGs from deps/heroicons
    const plugin = require("tailwindcss/plugin")
    const fs = require("fs")
    const path = require("path")

    module.exports = plugin(function ({ matchComponents, theme }) {
      let iconsDir = path.join(__dirname, "../../deps/heroicons/optimized")
      let values = {}
      let icons = [
        ["", "/24/outline"],
        ["-solid", "/24/solid"],
        ["-mini", "/20/solid"],
        ["-micro", "/16/solid"],
      ]
      icons.forEach(([suffix, dir]) => {
        let fullDir = path.join(iconsDir, dir)
        if (!fs.existsSync(fullDir)) return
        fs.readdirSync(fullDir).forEach((file) => {
          let name = path.basename(file, ".svg") + suffix
          values[name] = { name, fullPath: path.join(fullDir, file) }
        })
      })
      matchComponents(
        {
          hero: ({ name, fullPath }) => {
            let content = fs.readFileSync(fullPath).toString().replace(/\\r?\\n|\\r/g, "")
            let size = theme("spacing.6", "1.5rem")
            return {
              [`--hero-${name}`]: `url('data:image/svg+xml;utf8,${content}')`,
              "-webkit-mask": `var(--hero-${name})`,
              mask: `var(--hero-${name})`,
              "mask-repeat": "no-repeat",
              "background-color": "currentColor",
              "vertical-align": "middle",
              display: "inline-block",
              width: size,
              height: size,
            }
          },
        },
        { values }
      )
    })
    """
  end
end
